### ISSUE TITLE
Putting Bitcoin Foundation logo on document

### ISSUE THREAD

**Issue by sressler** [btcfoundationedcom/btcfoundationedcom.github.io#28]
Soooo I'd like to place the bitcoin foundation logo on the top of the "technical guide for non-technical people" 2 page document...clearly someone in the foundation needs to "approve" this. Anyone have any suggestions on the best way to do this?

**Comment by ABISprotocol** [comment]
No-one has objected since October 2014, so I'm closing this issue.
