### ISSUE TITLE
Inquiry Regarding Letter and Response

### ISSUE THREAD

**Issue by ABISprotocol** [btcfoundationedcom/btcfoundationedcom.github.io#31]
This is a inquiry with respect to an e-mail sent to @pmlaw (Executive Director of the Bitcoin Foundation).  A link to my inquiry can be seen [here](https://groups.google.com/d/msg/bitcoin-foundation-education-committee/6FiAcS_kycc/bQNvWmvLKP8J).  You are welcome to comment either here or in the google groups thread.

**Comment by ABISprotocol** [comment]
Summary of progress from Inquiry regarding Letter and Response (summarizing from google groups notes / e-mail commentary gathered from the time this issue was launched approximately one month ago) - EdComm has worked w/ @pmlaw to establish development of microsite based on bitcoinfoundation.org (e.g. bitcoinfoundation.org/EduComm) which would allow people to continue to contribute through github and maintain content that appears on the microsite.  (In progress)

**Comment by ABISprotocol** [comment]
This effort began in late 2014, and now has been realized with the launch of a [microsite for the Education Committee](http://bitcoinfoundationsandbox.org/education/) which is currently in sandbox or testing stage.  Additionally, per our suggestions, other committees also will be able to have their microsites on the Bitcoin Foundation page as well and members or contributors will be able to help with the management of content. @BruceFenton

**Comment by ABISprotocol** [comment]
This item is now completed, see:  https://bitcoinfoundation.org/education/

**Comment by ABISprotocol** [comment]
This item is needing to be re-opened due to that someone associated with the Foundation has made the decision to bump the Education Committee and other Committee content off the front page.  This is not adequate or acceptable and must be remedied.  @BruceFenton

**Comment by BruceFenton** [comment]
Hi, can you please send text and links and we will post

**Comment by ABISprotocol** [comment]
Hello Bruce, as of around 15 to 20 days ago (and I believe actually more) the new Bitcoin Foundation site displayed a dropdown menu on the frontpage which had links to active or known committees (such as the Education Committee and others) as well as interest areas (poverty, advocacy, etc).  Some of the sections were more developed than others.  

The Education Committee's content can be seen at  https://bitcoinfoundation.org/education/ and it is still active, but it is no longer visible by way of a link from the front page as it was before.  

Here is the content regarding Advocacy which I referred to. https://bitcoinfoundation.org/advocacy/

Here is the content regarding Regulatory https://bitcoinfoundation.org/regulatory-affairs/

Again, some committee content is more developed out than others, but I know for a fact that in the early stages of development of the new site, much effort was put into contacting the Chairs of all the committees to inform them of the transition to the new site and that the committee's content would be made more "front and center" as it were.

This all needs to be corrected so that there is once again a drop-down menu which offers visitors to the front page of bitcoinfoundation.org the ability to select from a drop-down menu the selection of what committees they would like to potentially visit.  The fact that the earlier version of the bitcoinfoundation.org page had this dropdown menu from the frontpage featuring the committees resulted in significantly more signups for the committees (at least, for the Education Committee) and more engagement with the Foundation from those who had signed up as a result.

Also, I have observed that I am no longer able to log in and contribute to the development of bitcoinfoundation.org as there is no login prompt for me.  If there is another place to go (github? some portal?) it would be good to let me know.

**Comment by BruceFenton** [comment]
I'll get on this and fix it or have it fixed.  With the Thanksgivng holiday it may take until after the weekend but if it's not done for some reason by Tuesday please ping me and I'll make sure to personally fix it.  Thanks

**Comment by BruceFenton** [comment]
I'll get this fixed.  With the holiday it might be after the weekend.

**Comment by ABISprotocol** [comment]
I can verify that this has now been fixed based on an observation of the 'Focus Areas' tab at https://bitcoinfoundation.org/ as of December 1, 2015.  The dropdown contains options for selection: Education, Advocacy, Adoption, Venture Capital, Poverty & Financial Inclusion, and Regulatory Affairs.  Looks good.  Thank you, Bruce.
